name: polymer_try_1
description: A sample web application
dependencies:
  bootjack: any
  http: any
  http_server: any
  json_object: any
  moviesbwu_components:
    path: ../moviesbwu_dartclient/moviesbwu_components
  polymer: any
  route: any
  vector_math: any
  yaml: any
dev_dependencies:
  unittest: any
transformers:
- polymer:
    entry_points:
    - web/alarm.html
