name: dtut
version: 0.0.1
description: An absolute bare-bones web app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular: '>=1.1.0 <1.2.0'
  browser: '>=0.10.0+2 <0.11.0'
  web_components: '>=0.3.3 <0.4.0'
