name: some
#sdk: '>=1.5.0 <2.0.0'
sdk: '>=1.9.0-dev.9.1 <2.0.0'
dependencies:
#  appengine: '>=0.3.0 <0.4.0'
#  browser: '>=0.10.0 <0.11.0'
#  polymer: '>=0.16.0 <0.17.0'
#  paper_elements: '>=0.7.0 <0.8.0'
#  redstone: '>=0.6.0-beta.1 <0.7.0'
  redstone_mapper: '0.2.0-beta.1 <0.3.0'
#  shelf: '>=0.6.0 <0.7.0'
#  shelf_static: '>=0.2.0 <0.3.0'
#  shelf_rpc: '>=0.0.0 <0.1.0'
#  route_hierarchical: '>=0.6.0 <0.7.0'
#  sass: '>=0.4.0 <0.5.0'
#  dartson: '>=0.2.0 <0.3.0'
#  analyzer: '>=0.15.6 <0.26.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
