name: so_36046599_test_query_child
dependencies:
  angular2: ^2.0.0-beta
  browser: ^0.10.0
  test: '>=0.12.12 <0.13.0'
  angular2_testing: '>=2.0.0-beta.11 <3.0.0'
dev_dependencies:
  dart_to_js_script_rewriter: ^0.1.0
transformers:
- angular2:
    entry_points:
    - web/main.dart
    - test/element_test.dart
    mirror_mode: verbose
    platform_pipes: 'package:angular2/common.dart#COMMON_PIPES'
# https://github.com/angular/angular/blob/3191fd144016c0873de4e3e24f0d8695a7d101c2/modules/angular2/src/common/pipes.ts
    gen_change_detection_debug_info: true
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    - 'package:angular2/router.dart#ROUTER_DIRECTIVES'

- test/pub_serve:
    $include: test/**_test{.*,}.dart

- $dart2js:
    minify: true
    commandLineOptions:
    - --dump-info
    - --show-package-warnings
    - --trust-type-annotations
    - --trust-primitives
- dart_to_js_script_rewriter
