name: playground_server
description: A sample web application
dependencies:
#  http: any
#  http_server: any
#  json_object: any
#  route: any
#  yaml: any
#  csvparser: any
#  couchclient: any
  di: any
  quiver: any
  sqljocky: any
#  route_hierarchical: any
#  sqljocky: any
  intl: any
#  crypto: any
#  charcode: any
#  benchmark_harness: any
#  typed_data: any
  xml: any
  #vector_math: any
  backy: any
  stack_trace: any
  cipher: '>=0.7.1 <0.8.0'
  bignum: '>=0.0.6 <0.1.0'
  reflectable: '>=0.1.0 <0.2.0'
  http: '>=0.11.3 <0.12.0'

dependency_overrides:
#  analyzer: ^0.24.0-dev.1

dev_dependencies:
  unittest: any
  mock: any
#  dart_lint:
#    git: git@github.com:dart-lang/dart_lint.git

transformers:
- reflectable:
    entry_points:
      - bin/reflectable/instance_of/main.dart
