name: playground
description: A sample web application
dependencies:
  angular: ^1.1.0
#  browser: any
#  http: any
#  http_server: any
#  json_object: any
#  route: any
#  yaml: any
#  csvparser: any
  di:
  quiver: any
#  google_maps: any
#  angular: any
#    git: git@github.com:angular/angular.dart.git
#  web_components: any
#  fontawesome_elements: any
#  route_hierarchical: any
#  sqljocky: any
#  intl: any
#  crypto: any
#  charcode: any
#  benchmark_harness: any
#  typed_data: any
#  rikulo_commons: any
  xml: any
#  bootjack: any
  #vector_math: any
#  fancy_button: any
  backy: any

dependency_overrides:
#  analyzer: ^0.24.0-dev.1

dev_dependencies:
  unittest: any
  mock: any
#  dart_lint:
#    git: git@github.com:dart-lang/dart_lint.git
