name: 'jspdf'
version: 0.0.1
description: A web app built using polymer.dart.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  paper_elements: '>=0.7.1 <0.8.0'
  polymer: '>=0.16.0 <0.17.0'
  core_elements: '>=0.7.1+2 <0.8.0'
transformers:
- polymer:
    entry_points: web/index.html
