name: content_child
dependencies:
  angular2: ^2.0.0-beta
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^0.1.0
transformers:
- angular2:
    entry_points:
    - web/main.dart
    mirror_mode: verbose
- $dart2js:
    minify: true
    commandLineOptions:
    - --dump-info
    - --show-package-warnings
    - --trust-type-annotations
    - --trust-primitives
- dart_to_js_script_rewriter
