name: shelf_playground
version: 0.0.1
description: A minimal web server using the shelf package.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.9.0-dev <2.0.0'
dependencies:
  args: any
  http: any
  quiver: any
  quiver_log: any
  shelf: ^0.6.0
  shelf_auth: any
  shelf_exception_response: any
  shelf_route: any

dev_dependencies:
  analyzer: any
  grinder:
    git: git@github.com:google/grinder.dart.git
  dart_style: ^0.1.7
  linter:
    git: git@github.com:dart-lang/linter.git
  bwu_utils_server: any

dependency_overrides:
  analyzer: ^0.25.0-dev.2
  args: ^0.13.0
  shelf: ^0.6.0
#  quiver: ^0.21.3
#  shelf: ^0.6.0
#  shelf_exception_response: ^0.1.1
