name: _template
environment:
  sdk: ">=1.2.0 <2.0.0"

dependencies:
  browser: ^0.10.0
  js: ^0.6.0-beta.4

dev_dependencies:
  test: ^0.12.3

transformers:
- test/pub_serve:
    $include: test/**_test{.*,}.dart

- $dart2js:
    minify: true

